### ISSUE TITLE
[Feature] Documentation Page Optimization Suggestions

### ISSUE THREAD

**Issue by yuluo-yx** [spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io#23]
## Background Description
Now the official website has been formed and is expected to be ready to go online soon. Still need to do some work before going live.

## Optimization Suggestion
- The document label needs to be supplemented and perfected, and some pages have the situation that `edit link` is unreachable，eg: https://github.com/spring-cloud-alibaba-group/spring-cloud-alibaba-group.github.io/blob/main/i18n/zh-cn/docusaurus-plugin-content-docs/current/overview/roadmap.md;
- It is necessary to uniformly specify the composition of document tags, and the format is not uniform. We can refer to [Docusaurus document title metadata](https://www.docusaurus.cn/docs/api/plugins/@docusaurus/plugin-content-docs# markdown-front-matter) formulated;
- The contribution documentation should be supplemented to facilitate the adjustment of the document format for students who are participating in the construction of the official website for the first time, while reducing the review workload;
- Collect FAQs and improve FAQ documents;
- Supplement the content of the community module on the official website, such as communication groups, community news and other information;
- We can add some new features to enrich the content of our documents when writing documents, for example: https://www.docusaurus.cn/docs/markdown-features/admonitions.
- Supplement FAQ documents and roadmap documents

## Task List
- [X] Add documentation formatting instructions  @yuluo-yx 
- [X] Optimize community module documentation @yuluo-yx 
- [X] Add FAQ and Roadmap @yuluo-yx

**Comment by yuluo-yx** [comment]
You can discuss the functions that need to be improved under this issue. If you are interested in improving the optimization points, you can claim the task.

**Comment by why-ohh** [comment]
NACOS
1注意给概述的图片背景色统一
2一些加粗的问题

 Seata
1进行资料补充

Sential
1.进阶部分：加粗问题、表格格式问题

 MQ：
1命令行$开头
2标题仅用《更多配置项》

 异构微服务
1格式调整，

静态编译
1删除进阶部分

最佳演示
1格式修改

最后：
1注意版本之间的差异，微服务治理模块只有2.x版本有
2All version文档内容不全，未发布的删除掉，修改错别字
3.注意每句话最后的符号问题。

**Comment by yuluo-yx** [comment]
> NACOS 1注意给概述的图片背景色统一 2一些加粗的问题
> 
> Seata 1进行资料补充
> 
> Sential 1.进阶部分：加粗问题、表格格式问题
> 
> MQ： 1命令行$开头 2标题仅用《更多配置项》
> 
> 异构微服务 1格式调整，
> 
> 静态编译 1删除进阶部分
> 
> 最佳演示 1格式修改
> 
> 最后： 1注意版本之间的差异，微服务治理模块只有2.x版本有 2All version文档内容不全，未发布的删除掉，修改错别字 3.注意每句话最后的符号问题。

- [ ] 格式修改 @yuluo-yx

**Comment by yuluo-yx** [comment]
此issue中得修改已全部完成，现关闭！
